// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHVFNxyyscvOruQE2-sUk1KDcgCwyk5m4',
    appId: '1:640276114476:web:7370a40afaf69ef3e2b589',
    messagingSenderId: '640276114476',
    projectId: 'chat-app-47c96',
    authDomain: 'chat-app-47c96.firebaseapp.com',
    storageBucket: 'chat-app-47c96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv3ifVvgrw4OXKARo_jTrGXEH3NsBRhhQ',
    appId: '1:640276114476:android:2708e9bff230a0d0e2b589',
    messagingSenderId: '640276114476',
    projectId: 'chat-app-47c96',
    storageBucket: 'chat-app-47c96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-5PwslnJ_x9MKSXhdbyAxF9tJZTJbd8',
    appId: '1:640276114476:ios:7aa574c01f76c8cce2b589',
    messagingSenderId: '640276114476',
    projectId: 'chat-app-47c96',
    storageBucket: 'chat-app-47c96.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf-5PwslnJ_x9MKSXhdbyAxF9tJZTJbd8',
    appId: '1:640276114476:ios:1e0b9e534b4b19a3e2b589',
    messagingSenderId: '640276114476',
    projectId: 'chat-app-47c96',
    storageBucket: 'chat-app-47c96.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
